In [1]:
# DIY layers
# the layer without parameters
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
# combine it as component with other layers
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()  # check if the mean of the output is 0, so that the CenteredLayer worked

tensor(6.5193e-09, grad_fn=<MeanBackward0>)

In [5]:
# layer with parameters
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.2918,  0.4324,  0.1227],
        [-0.1844,  1.2991, -0.6063],
        [-1.5857, -1.0503,  0.0604],
        [-0.2598,  0.2105,  0.8041],
        [-2.4738,  0.2445,  0.2824]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))  # forward propagation

tensor([[0.0000, 2.0704, 1.1210],
        [0.0000, 0.9714, 1.4922]], grad_fn=<ReluBackward0>)

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[6.5964],
        [8.5150]], grad_fn=<ReluBackward0>)