In [1]:
# IO
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')
x1 = torch.load('x-file')
x1

tensor([0, 1, 2, 3])

In [2]:
y = torch.zeros(4)
torch.save([x, y], 'x-files.txt')
x1, y1 = torch.load('x-files.txt')
(x1, y1)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [3]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [4]:
torch.save(net.state_dict(), 'mlp.params')

In [5]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()  # switch to evaluate mode, which will not execute dropout

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [6]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])