In [1]:
import torch

# scalar quantity represented by a tensor which only has one element
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x ** y

# vector could be regard as a list formed by scalar quantities. Normally, it has no limitations to its length
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [2]:
x[3]

tensor(3)

In [3]:
len(x), x.shape

(4, torch.Size([4]))

In [4]:
# extend a vector into two dimensional space will generate a matrix
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [5]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [6]:
# vector is the extension of scalar quantity, and matrix is the extension of the vector
# tensor is a general method to describe a n-dimensional array which could as any number of directions
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()  # give a copy of A to B by distribute new memories
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [9]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [10]:
# use a scalar quantity to add or multi a tensor will not change the shape of tensor. Instead, it is a element-wise operation
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [11]:
# use the sum() will decrease the dimension of the tensor in all direction and turns it into a scalar quantity
# on some situations, we could decide the tensor will decrease its dimension along with which axis

A_sum_axis0 = A.sum(axis=0)
A.shape, A_sum_axis0, A_sum_axis0.shape

(torch.Size([5, 4]), tensor([40., 45., 50., 55.]), torch.Size([4]))

In [12]:
A_sum_axis1 = A.sum(axis=1)
A.shape, A_sum_axis1, A_sum_axis1.shape

(torch.Size([5, 4]), tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [13]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [14]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [15]:
# compute means or sums with the fixed axis
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [16]:
# use the broadcast to divide
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [17]:
# compute the sum with stable shape, while the results will be placed in the last of the tensor
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [19]:
# dot product
x = torch.tensor(x, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

C:\Users\Leanne\AppData\Local\Temp\ipykernel_40988\4139098931.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32)


(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [20]:
torch.sum(x * y)

tensor(6.)

In [21]:
# products between the matrix and vector
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [22]:
# products between the matrix and matrix
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [23]:
# norm of the vector is the function f which maps the vector into the scalar quantity
# normally, we will calculate the L2 norm of the vector, which is actually the square root of the sum of the square of each element
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [24]:
# L1 norm is the sum of the abs of each element in the vector
torch.abs(u).sum()

tensor(7.)

In [25]:
# Frobenius norm of the matrix X is the square root of the sum of the square of elements in the matrix. We can regard it as the matrix version of the L2 norm of vector
torch.norm(torch.ones((4,9)))

tensor(6.)