In [1]:
# example: derivation of the y=2X.T*X
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)
x.grad

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
# use the backward propagate function to automatically compute the gradient of y to elements in the x, which should be 4x
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
# in default situation, pytorch will store the gradient. So we have to clear the values before the next operations
x.grad.zero_()

y = x.sum()
print(y)
y.backward()
x.grad

tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])

In [7]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [8]:
# detach compute: for example, assume y is the function of x, z is the function of x & y. When we compute the gradient of the z, sometimes we want to regard the y as constant
x.grad.zero_()
y = x * x
# u has the same value with y, but it will abort the information in the compute graph about how to use y
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [11]:
# use the control flow to compute the gradient
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [12]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [13]:
a.grad == d / a

tensor(True)